// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Free-form agent identity surfaced into the dev-loop / task-run
 * system prompt's `<agent_identity>` section.
 *
 * Every field is best-effort prose: aura-os reads it off the
 * `agent_instance` row, the harness splices it into the prompt
 * verbatim. Empty / blank fields are dropped at render time so an
 * uninitialised wire payload (PR B's default) produces no model-facing
 * bytes.
 */
export type AgentIdentityWire = { name: string, role: string, personality: string, };
