// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilesChanged } from "./FilesChanged";
import type { SessionUsage } from "./SessionUsage";

/**
 * Payload for `assistant_message_end`.
 */
export type AssistantMessageEnd = { message_id: string, stop_reason: string, usage: SessionUsage, files_changed: FilesChanged, };
