// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalResponse } from "./ApprovalResponse";
import type { SessionInit } from "./SessionInit";
import type { UserMessage } from "./UserMessage";

/**
 * Top-level inbound message envelope.
 */
export type InboundMessage = { "type": "session_init" } & SessionInit | { "type": "user_message" } & UserMessage | { "type": "cancel" } | { "type": "approval_response" } & ApprovalResponse;
