// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";
import type { ToolAuth } from "./ToolAuth";

/**
 * Definition for an installed tool, sent over the wire in `session_init`.
 *
 * Wire-compatible with `aura_core::InstalledToolDefinition` but
 * self-contained so this crate has no dependency on `aura-core`.
 */
export type InstalledTool = { name: string, description: string, input_schema: JsonValue, endpoint: string, auth: ToolAuth, timeout_ms: bigint | null, namespace: string | null, metadata: { [key in string]?: JsonValue }, };
