// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantMessageEnd } from "./AssistantMessageEnd";
import type { AssistantMessageStart } from "./AssistantMessageStart";
import type { ErrorMsg } from "./ErrorMsg";
import type { SessionReady } from "./SessionReady";
import type { TextDelta } from "./TextDelta";
import type { ThinkingDelta } from "./ThinkingDelta";
import type { ToolResultMsg } from "./ToolResultMsg";
import type { ToolUseStart } from "./ToolUseStart";

/**
 * Top-level outbound message envelope.
 */
export type OutboundMessage = { "type": "session_ready" } & SessionReady | { "type": "assistant_message_start" } & AssistantMessageStart | { "type": "text_delta" } & TextDelta | { "type": "thinking_delta" } & ThinkingDelta | { "type": "tool_use_start" } & ToolUseStart | { "type": "tool_result" } & ToolResultMsg | { "type": "assistant_message_end" } & AssistantMessageEnd | { "type": "error" } & ErrorMsg;
