// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentIdentityWire } from "./AgentIdentityWire";
import type { AgentPermissionsWire } from "./AgentPermissionsWire";
import type { AgentToolPermissionsWire } from "./AgentToolPermissionsWire";
import type { ChatProjectInfoWire } from "./ChatProjectInfoWire";
import type { ConversationMessage } from "./ConversationMessage";
import type { InstalledIntegration } from "./InstalledIntegration";
import type { InstalledTool } from "./InstalledTool";
import type { IntentClassifierSpec } from "./IntentClassifierSpec";
import type { SessionModelOverrides } from "./SessionModelOverrides";

/**
 * Payload for `session_init`.
 */
export type SessionInit = { system_prompt: string | null, 
/**
 * Model identifier (e.g., "claude-opus-4-6").
 */
model: string | null, 
/**
 * Maximum tokens per model response.
 */
max_tokens: number | null, 
/**
 * Sampling temperature.
 */
temperature: number | null, 
/**
 * Maximum agentic steps per turn.
 */
max_turns: number | null, 
/**
 * Installed tools to register for this session.
 */
installed_tools: Array<InstalledTool> | null, 
/**
 * Installed integrations authorized for this session.
 */
installed_integrations: Array<InstalledIntegration> | null, 
/**
 * Workspace directory path (must be under the server's workspace base).
 */
workspace: string | null, 
/**
 * Absolute path to the real project directory on the host filesystem.
 * When set, tool execution happens directly in this directory instead of
 * the sandboxed `aura_data/workspaces/` tree.
 */
project_path: string | null, 
/**
 * JWT auth token for proxy routing.
 */
token: string | null, 
/**
 * Project ID for domain tool calls (specs, tasks, etc.).
 */
project_id: string | null, 
/**
 * Prior conversation messages to restore into session history.
 */
conversation_messages: Array<ConversationMessage> | null, 
/**
 * Project-agent UUID for X-Aura-Agent-Id billing header.
 */
aura_agent_id: string | null, 
/**
 * Storage session UUID for X-Aura-Session-Id billing header.
 */
aura_session_id: string | null, 
/**
 * Organization UUID for X-Aura-Org-Id billing header.
 */
aura_org_id: string | null, 
/**
 * Harness-level agent ID for per-agent skill lookup. Set by the
 * caller (e.g. aura-os) so the harness can resolve which skills
 * are installed for this agent and which `Session.agent_id`
 * hashes to take a turn-lock against.
 *
 * The string is opaque to the harness, but `aura-os` constructs
 * it via `aura_os_core::harness_agent_id` in one of three forms:
 *
 * - `{template}::default` — bare-agent / loop / single-task /
 *   public-chat surfaces with no [`AgentInstance`] or storage
 *   session axis.
 * - `{template}::{agent_instance_id}` — classic per-instance
 *   partition used by automaton runs and any chat surface that
 *   opts out of session-level partitioning.
 * - `{template}::{agent_instance_id}::{session_id}` — full
 *   per-(instance, storage_session) partition. Phase 1 of the
 *   parallel-session-chats plan threads the resolved storage
 *   `session_id` into the third segment from
 *   `agent_route.rs` and `instance_route.rs`, so two chat POSTs
 *   against the same `(template, instance)` with different
 *   `session_id` values get distinct `Session.agent_id` values
 *   in the harness, distinct record logs, and distinct
 *   turn-locks — i.e. they run concurrently end-to-end.
 *
 * The harness path treats this field as a hex-or-string fallback:
 * `Session.agent_id = AgentId::from_hex(...).unwrap_or_else(|| blake3(...))`.
 * Three-segment strings therefore hash through blake3 and two
 * strings differing only in the session segment land on
 * distinct `AgentId`s. `parse_agent_id` (router/ids.rs) already
 * strips at the first `::` so per-agent skill lookup keeps
 * matching the template across all three forms.
 *
 * [`AgentInstance`]: aura_os_core::AgentInstance
 */
agent_id: string | null, 
/**
 * Template agent id for skill / permissions / billing lookup.
 *
 * `agent_id` (above) is the partition key the harness uses for
 * turn-locking, derived from the AgentInstance via
 * `aura_os_core::harness_agent_id` (one of the three forms
 * listed there). `template_agent_id` is the stable Aura template
 * id (the row in `agents`) so the harness can resolve installed
 * skills, agent-level permissions, and billing aggregation
 * against a single identity per template even when multiple
 * partitions (per-instance, per-session) exist.
 *
 * Optional during rollout: when `None`, the harness falls back
 * to `agent_id` for skill lookup (the pre-Phase-1 behavior).
 */
template_agent_id: string | null, 
/**
 * Originating end-user id for resolving and persisting tool defaults.
 */
user_id: string, 
/**
 * Optional per-session model overrides applied on top of the
 * harness's env-default router config. `None` means "use the
 * harness's defaults verbatim".
 */
provider_overrides: SessionModelOverrides | null, 
/**
 * Optional keyword-driven intent classifier spec. When present the harness
 * narrows the per-turn tool surface based on each user message using the
 * same tier-1 / tier-2 domain rules aura-os used to run in-process for
 * the CEO-preset agent. Ships as the profile-JSON subset that
 * `aura-tools::IntentClassifier::from_profile_json` accepts, plus a
 * `tool_domains` map from tool name to domain so the harness can narrow
 * `tool_definitions` (which are opaque to the classifier otherwise).
 */
intent_classifier: IntentClassifierSpec | null, 
/**
 * Explicit [`AgentPermissionsWire`] bundle for this session. Required
 * on every session; the harness enforces scope + capability checks
 * unconditionally against these grants. See the module-level
 * "Agent permissions model" section for details.
 */
agent_permissions: AgentPermissionsWire, 
/**
 * Optional per-agent tool override stamped onto this session. `None`
 * means the harness should load the persisted agent override, if any;
 * an empty map means "explicitly inherit the user default".
 */
tool_permissions: AgentToolPermissionsWire | null, 
/**
 * Chat-WS migration: typed agent identity (name / role /
 * personality) the harness's `SystemPromptBuilder` consumes for
 * the chat path's `<agent_identity>` section. Mirrors the
 * dev-loop wire field on `AutomatonStartRequest`. When absent or
 * every sub-field is blank, the harness keeps `<agent_identity>`
 * out of the assembled prompt and — together with the other
 * typed fields — falls back to the legacy
 * [`SessionInit::system_prompt`] path for backward compatibility
 * with older callers.
 */
agent_identity: AgentIdentityWire | null, 
/**
 * Chat-WS migration: operator-curated skills list rendered as
 * `<agent_skills>`. Empty list ⇒ the harness drops the section
 * entirely.
 */
agent_skills: Array<string>, 
/**
 * Chat-WS migration: operator-authored system prompt (the
 * "system prompt" textarea on the agent template, plus any
 * server-baked addenda such as the project-state continuity
 * snapshot or plan-mode suffix). Empty / `None` ⇒ no
 * `<agent_system_prompt>` section is rendered.
 */
agent_system_prompt: string | null, 
/**
 * Chat-WS migration: typed project descriptor consumed by the
 * harness's `SystemPromptBuilder.project_context()`. When
 * populated, the harness assembles the chat system prompt via
 * the builder's `chat_capabilities + project_context + agents_md`
 * preset (plus identity sections when set) and ignores the
 * legacy [`SessionInit::system_prompt`] field.
 */
project_info: ChatProjectInfoWire | null, };
