// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationMessage } from "./ConversationMessage";
import type { InstalledTool } from "./InstalledTool";

/**
 * Payload for `session_init`.
 */
export type SessionInit = { system_prompt: string | null, 
/**
 * Model identifier (e.g., "claude-opus-4-6").
 */
model: string | null, 
/**
 * Maximum tokens per model response.
 */
max_tokens: number | null, 
/**
 * Sampling temperature.
 */
temperature: number | null, 
/**
 * Maximum agentic steps per turn.
 */
max_turns: number | null, 
/**
 * Installed tools to register for this session.
 */
installed_tools: Array<InstalledTool> | null, 
/**
 * Workspace directory path (must be under the server's workspace base).
 */
workspace: string | null, 
/**
 * Absolute path to the real project directory on the host filesystem.
 * When set, tool execution happens directly in this directory instead of
 * the sandboxed `aura_data/workspaces/` tree.
 */
project_path: string | null, 
/**
 * JWT auth token for proxy routing.
 */
token: string | null, 
/**
 * Project ID for domain tool calls (specs, tasks, etc.).
 */
project_id: string | null, 
/**
 * Prior conversation messages to restore into session history.
 */
conversation_messages: Array<ConversationMessage> | null, 
/**
 * Project-agent UUID for X-Aura-Agent-Id billing header.
 */
aura_agent_id: string | null, 
/**
 * Storage session UUID for X-Aura-Session-Id billing header.
 */
aura_session_id: string | null, 
/**
 * Organization UUID for X-Aura-Org-Id billing header.
 */
aura_org_id: string | null, };
