// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage information for a session.
 */
export type SessionUsage = { input_tokens: bigint, output_tokens: bigint, cumulative_input_tokens: bigint, cumulative_output_tokens: bigint, 
/**
 * Fraction of the model's context window consumed (0.0–1.0).
 */
context_utilization: number, 
/**
 * Model identifier used for this turn.
 */
model: string, 
/**
 * Provider name (e.g., "anthropic").
 */
provider: string, };
