// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolInfo } from "./ToolInfo";

/**
 * Payload for `session_ready`.
 */
export type SessionReady = { session_id: string, tools: Array<ToolInfo>, };
