// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversationMessage } from "./ConversationMessage";
import type { InstalledTool } from "./InstalledTool";

/**
 * Payload for `session_init`.
 */
export type SessionInit = { system_prompt: string | null, 
/**
 * Model identifier (e.g., "claude-opus-4-6").
 */
model: string | null, 
/**
 * Maximum tokens per model response.
 */
max_tokens: number | null, 
/**
 * Sampling temperature.
 */
temperature: number | null, 
/**
 * Maximum agentic steps per turn.
 */
max_turns: number | null, 
/**
 * Installed tools to register for this session.
 */
installed_tools: Array<InstalledTool> | null, 
/**
 * Workspace directory path.
 */
workspace: string | null, 
/**
 * JWT auth token for proxy routing.
 */
token: string | null, 
/**
 * Project ID for domain tool calls (specs, tasks, etc.).
 */
project_id: string | null, 
/**
 * Prior conversation messages to restore into session history.
 */
conversation_messages: Array<ConversationMessage> | null, };
